### ISSUE TITLE
Milestone v3 alpha 5

### ISSUE THREAD

**Issue by stevenhoving** [stevenhoving/camstudio#50]
List of tasks before we can release a new alpha:
- [ ] fix record window (currently causes crashes or records invalid data or invalid part of the display).
- [ ] verify multi display rect recording (record section of display 1 and a section of display 2).
- [ ] integrate msvc runtime installer into installer.
